language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-basicfrontend' ]; then cd .. && eval "mv $currentfolder generator-basicfrontend" && cd generator-basicfrontend; fi
